FROM php:7.4-apache

RUN docker-php-ext-install mysqli

# Update the Apache configuration file
RUN sed -i 's/Listen 80/Listen 0.0.0.0:80/g' /etc/apache2/ports.conf
RUN sed -i 's/<VirtualHost \\*:[^>]*>/<VirtualHost *:80>/g' /etc/apache2/sites-available/000-default.conf